# Generated by Django 4.1 on 2022-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='categorias',
            field=models.CharField(choices=[('Outros', 'Outros'), ('Salário', 'Salario'), ('Extras', 'Extras'), ('Bonificação', 'Bonificacao')], default='Outros', max_length=11),
        ),
    ]
